captions:
  # General
  - Free! # don't change
  - Someone isn't on time
  - Last minute flaker
  - Tank dies last
  - Hunter didn't do mechanics
  - Hunters pull extra ads
  - Rouge clocks entire raid
  - Wipe on ads
  - A melee DPS is flamed for not switching to ads
  - East Coaster(s) ignore mechanic for dps increase
  - Boss is accidentally pulled
  - Missed dispel
  - Someone dies to frontal cone
  - Lust is used at completely the wrong time
  - Kick rotation is out of order
  # - Missing consumables
  - Pulled incorrectly timer
  - Release after "Do not release" is called
  - Lazy POS asks for summons
  - Cauldron dropped after personal flask(s) used
  # - Multiple feasts for hungry raiders
  - Too many chefs in the kitchen
  - PUGs ended raid night
  - All 12 classes present in raid
  - An old guildie returns to raid
  - BoE drops
  - Brain shout
  - 'CLEAR COMMS!!!'
  - Delays summoning because someone forgot to turn off war mode # Not really applicable for this one
  - Guildie posts in general
  - New boss killed
  - Overrun by boss adds
  - Raid Whiskey IRL
  - Completed Lion Dragon
  - DPS complaining about their parse
  - Transformed into a Turkey

  # Raid Specific
  - Ate a donut
  - Ate multiple donuts
  - Talking sword draws first blood
  - Died in a puddle
  - Shimmy to the right
  - Dog pounced
  - Deathly *RAWR*
  - Pop an orb
  - 'You have been ejected'
  - Additional trash pulled
  - Portals less than 10 ft apart
  - Seed of Extinction
  - Annihilated
  - Slipped on arcane banana peel
  - Donated too much blood
  - Stood in fire
  - Rain of Fire
  - Bottle shatters
  - Anima web hits entire raid
  - Condemn
  - Dreadbolt Volley
  - Killed partner
  - Hateful Gaze
  - Feared to Death
  - Bleed to Death
  - Meteor to the Head
  - Stoned
  - Marched Too Slowly
  - Yeeted into Anima Maelstorm

  # People Specific
  - Wash Dog calls for buffs
  - Pinecone complains about buffs
  - Pinecone made money from gambling
  - Cone having a cone-spasm
  - GM listening to democracy
  - Clayton starts singing
  # - Climbvia is bankrupt
  - Donra is flamed
  - Donra caught flame whispering
  # - 'Why are you dead Donra?'
  - Donra takes Charles life
  # - Buukers never dies during raid
  # - Ribuukers falls off a ledge :^)
  - Bonesoup asks for innervate on CD
  - Not Bonesoup asks for innervate
  - Stephen tricking not a Tank
  - Jason makes money from the house
  - Jason swearing
  - Weeb Phrase
  - Bar is top DPS
  - 'Which Andy?'
  - "I'm (*)andy"
  - Andy swaps to a new class
  - Sunny D
  # - 'Can I ams this'
  - 'P U M P I N'
  - Woody compliments raid
  - Dick shen orange parses
  - Helya is back
