captions:
  # General
  - Free! # don't change
  - Someone isn't on time
  - Last minute flaker
  - Tank dies last
  - Hunter didn't do mechanics
  - Hunters pull extra ads
  - Wipe on ads
  - A melee DPS is flamed for not switching to ads
  - East Coaster(s) ignore mechanic for dps increase
  - Boss is accidentally pulled
  - Missed dispel
  - 'One hour in: “OH LOL I FORGOT TO FLASK”'
  - Someone dies to frontal cone
  - Lust is used at completely the wrong time
  - Kick rotation is out of order
  - Missing consumables
  - "Wait I need food buff, don't pull"
  - Bone soup pun
  - Pulled incorrectly timer
  - Release after "Do not release" is called
  - Lazy POS asks for summons
  - Cauldron dropped after personal flask(s) used
  - Multiple feasts for hungry raiders
  - Too many chefs in the kitchen
  - PUGs ended raid night
  - All 12 classes present in raid
  - An old guildie returns to raid
  - BoE drops
  - Brain shout
  - "CLEAR COMMS!!!"
  - Delays summoning because someone forgot to turn off war mode # Not really applicable for this one
  - Guildie posts in general
  - New boss killed

  # Raid Specific
  - "My corruption gear isn't the problem"
  - T-Boned
  - Cataclysm kills someone
  - Someone knocked off
  - Mount running off the ledge
  - Jumps into gapping hole and dies
  - Death by DPS reflection
  - One shot death by Vexonia Breath
  - Failed to score
  - 'GOAL!'
  - Shadow Bolt Volley
  - Death by soccer ball
  - Someone trampled to death
  - '"The boss was at 1 health" and wiped'
  - Overrun by boss adds
  - Roly-polyed
  - Mochi dog not fed mochi
  - Elevator death
  - VITA strikes entire raid
  - Someone dies outside of Maut puddle
  - Unstable void missle not soaked
  - Tentacle slammed
  - Carapace eyeball kicked
  - Death by Paranoia
  - Nzoth MCs someone
  - Nzoth draws blood in Phase 1
  - Someone kicks Jaina
  - Ads pulled during stealth

  # People Specific
  - Pinecone got charmed
  - Pinecone complains about buffs
  - Pinecone made money from gambling
  - Donra is flamed
  - 'Why are you dead Donra?'
  - Donra takes Charles life
  - Buukers never dies during raid
  - Ribuukers falls off a ledge :^)
  - Bonesoup asks for innervate on CD
  - Not Bonesoup asks for innervate
  - Bone soup pun
  - Bee fact
  - 'Mah leg!'
  - May or may not be ___
  - Jason swearing
  - Weeb Phrase
  - Bar is top DPS
  - Tank flames Bar
  - 'Which Andy?'
  - "I'm Randy"
  - Sunny D
  - Arnold doesn't have an orange parse
  - Arnold being a terrorist
  - 'Can I ams this'
  - Woody compliments raid
#  - Dick shen orange parses